### PR TITLE
343: Reducing bureaucracy

### PR DESCRIPTION
**Pull request by pimotte**
書いてはいけません。＝ (You) must write.

I explicitly claim 0.1 points for the quote that used to be in the original PR message.

### CODE REVIEW

**Comment by MrHug** [comment]
IF there is no longer Donald Trump quote in this PR THEN :+1:

**Comment by jdonkervliet** [comment]
IF there remains a Donal Trump quote in this PR until merge THEN :+1:

**Comment by MrHug** [comment]
xD Seems like @ManInTheGitHub will be required to decide this ;)

**Comment by pimotte** [comment]
I have a bonus quote for both of you. 

"Fuck you" -Linus Torvalds

**Comment by jdonkervliet** [comment]
:+1:

**Comment by pimotte** [comment]
According to 333 the PR should contain a quote in the original PR message. Does this mean that I can remove the message and follow it up by a merge. I feel like technically it shouldn't help to put another quote there, because that's not the original pull request message.

**Comment by MrHug** [comment]
I have no objection to that line of reasoning. Though you should keep rule 336 in mind ;)

**Comment by pimotte** [comment]
I'm resolving the condition in https://github.com/pimotte/nomic/pull/71#issuecomment-227155355 to be true, because there is no such quote in the PR. This means the vote resolves to :+1:

That makes 3/4. I'm merging.

**Pull request merged**
