### PR TITLE
314: Merge commit tolerance

### PR DESCRIPTION
**Pull request by pimotte**
For convenience and profit. Mostly convenience.

### CODE REVIEW

**Comment by jdonkervliet** [comment]
Is this a rule-change?

**Comment by MrHug** [comment]
Why wouldn't it be? It changes not only the language but also effect of the rule...?

**Comment by jdonkervliet** [comment]
Fair enough. I missed the new sentence because whitespace was also altered. How much can you do with a merge commit? If you can abuse that by insert that arbitrary changes it will break everything.

**Comment by MrHug** [comment]
I agree. In conflict resolution anything can be added.

I think a better alternative would be something along the lines of "a merge commit that changes nothing in the proposed rule-change" or sth along those lines.

**Comment by pimotte** [comment]
Note that changing rules without the rules allowing it is already disallowed (116). Furthermore, (106) already specifies that rules are to be adopted in the form in which they were voted on, so merge commits which mess stuff up significantly are in fact against the rules. Keep in mind that github is really more a tool than a rule-enforcement machine. To me it is, anyway. I would be open to a more explicit formulation, but I'd prefer to keep this one.

**Comment by MrHug** [comment]
Hmmm I suppose those are valid points, yet I would like it a lot more if you add the words ", that does not change the proposed rule".

**Comment by jdonkervliet** [comment]
Good point Pim. I don't pay that much attention to the rules in this game. :sweat_smile:

**Comment by MrHug** [comment]
:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by arthurbik** [comment]
:+1:

**Comment by pimotte** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 306, I will merge this pull request.

**Pull request merged**
