### PR TITLE
350: Safely Opening

### PR DESCRIPTION
**Pull request by MrHug**
We discussed this earlier, I think we should have it.

0.1 points for

> "We keep moving forward, opening new doors, and doing new things, because we're curious and curiosity keeps leading us down new paths." (Walt Disney)

### CODE REVIEW

**Comment by pimotte** [comment]
This would probably move all of the weight onto merging. I'm not necessarily against that, but it should be a factor in consideration.

**Comment by jdonkervliet** [comment]
As said in verbal discussion: this would allow a player to open a PR while their turn is frozen (for instance when they are on trial).

**Comment by MrHug** [comment]
I've included a clause to deal with @jdonkervliet's valid comment.

**Comment by jdonkervliet** [comment]
Looks reasonable now.

**Comment by jdonkervliet** [comment]
:+1:

**Comment by pimotte** [comment]
If a rules prohibits opening an issue, then this enables you to open an issue. Is this by design?

**Comment by MrHug** [comment]
Hmm no it wasn't and it could be a problem with Trial participants going on Hiatus. Fixing now.

**Comment by MrHug** [comment]
Well looks like I have somehow screwed over the git history of this branch... Somehow I have managed to get @ManInTheGitHub's PR in here and it shows up as a difference to master for some reason?

**Comment by MrHug** [comment]
Ok merging master back in fixed things...

Anway @jdonkervliet your vote is now invalid ;)

**Comment by ManInTheGitHub** [comment]
Given that I'm still quite likely to do things incorrectly here, this looks fine by me :)

**Comment by ManInTheGitHub** [comment]
:+1:

**Comment by pimotte** [comment]
If opening an issue is prohibited, a player could be put on trial for opening a pull request that does not adhere to all the rules.

**Comment by MrHug** [comment]
Fixed, @ManInTheGitHub your vote is now invalid again ;(

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
With 3/4 votes, this can be merged.

**Pull request merged**
