### PR TITLE
340: Enabling trophies through mutable change

### PR DESCRIPTION
**Pull request by pimotte**
Replaces #58

人は勝ちますなら、新しい競技が始まります。If a person wins, a new game starts.

### CODE REVIEW

**Comment by MrHug** [comment]
Yeah this looks far better

**Comment by MrHug** [comment]
:+1:

**Comment by jdonkervliet** [comment]
Yeah, I think this is good.

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
With 3 out of 4 players voting in favour, this can be merged.

**Pull request merged**
