### PR TITLE
334: Making Japanese/Turkish less strict

### PR DESCRIPTION
**Pull request by pimotte**
"Die Grenzen meiner Sprache bedeuten die Grenzen meiner Welt." -Ludwig Wittgenstein

今やりますより易しいです。= Now, playing is easier.

### CODE REVIEW

**Comment by MrHug** [comment]
Meh, I quite liked the old rule.

**Comment by MrHug** [comment]
:-1:

**Comment by pimotte** [comment]
Really? I'll probably think about it more if I get points (since I have to pre-include them in the PR) and it won't be as disruptive to gameplay as the other rule.

**Comment by MrHug** [comment]
Meh, you just shouldn't forget about it in the PR in my opinion. I want some rules that make the process of getting a PR accepted at least a little work. I know it's quite disruptive, but as editing posts is currently allowed, you can always just go the @jdonkervliet route and edit your first message ;) EDIT: In other words, validating votes.

**Comment by pimotte** [comment]
If we informally judge that as being allowed, I'll do that for now. But that seems kind of iffy in general.

**Comment by MrHug** [comment]
Well we haven't put @jdonkervliet on Trial for doing it in the past (see for instance #45)...

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by pimotte** [comment]
I'm aware, I'm just saying I might make a rule disallowing edits at some point.

**Comment by pimotte** [comment]
But 2 vs 1 makes this easier.

**Pull request merged**
