### PR TITLE
332: Undo some damage

### PR DESCRIPTION
**Pull request by jdonkervliet**
I'm actually not sure why I voted in favor of #48. :cry:

Pim çok kötü bir adam. - Pim is a very bad man.

### CODE REVIEW

**Comment by jdonkervliet** [comment]
On hold because of #52, more specifically: https://github.com/pimotte/nomic/issues/52#issuecomment-224275473

**Comment by pimotte** [comment]
While I have no significant objections to this removal, and I mostly added this to enable #52, I do think it is a nice construction, which allows some room for actually winning a trophy if people aren't careful formulating rules.

**Comment by jdonkervliet** [comment]
Should we not remove this entire rule because of its conflict with 112?

**Comment by pimotte** [comment]
We could, but we don't necessarily need to, since at this point in time it is void anyway. In particular, I would like to have the first half of this rule anyway, so I'd to make 112 mutable at some point.

**Comment by pimotte** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by pimotte** [comment]
2/3 votes is in.

**Pull request merged**
