### PR TITLE
309: Include rule-change number in title of PR

### PR DESCRIPTION
**Pull request by pimotte**
This will enable us to easily view the existing PRs and determine which number should be attached to the rule-change.

### CODE REVIEW

**Comment by MrHug** [comment]
Did I just miss one, or should this be labelled 308?

EDIT: If so, this PR is in violation of rule 108.

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
I was assuming #12 was 307 and #15 was 308.

**Comment by MrHug** [comment]
But they are 306 and 307, is that a mistake on @jdonkervliet and my part then?

**Comment by pimotte** [comment]
#12 cannot be 306, because #11 has been merged as 306. (You can see why 309 exists:P)

**Comment by MrHug** [comment]
Right... I will update #15 to 308 then :)
And yeah 309 sounds good to me still :)

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
You already voted, but I appreciate the support ;)

**Comment by MrHug** [comment]
Oh right I did ;P

**Comment by jdonkervliet** [comment]
:+1:

**Comment by jdonkervliet** [comment]
With 3 votes in favour, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 214, I will merge this pull request.

**Comment by MrHug** [comment]
Will you solve the merge conflict then? Cause technically speaking I think @pimotte has to solve that and we need to have a vote again ;)

EDIT: Admittedly I don't know where the conflict comes from

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 306, I will merge this pull request.

**Pull request merged**
