### PR TITLE
Voting mechanism change

### PR DESCRIPTION
**Pull request by jdonkervliet**
Voting with emoticons. Makes voting a clean and concise process, and makes it easy for future bots to do merging.

### CODE REVIEW

**Comment by pimotte** [comment]
I **vote** in favour.

**Comment by MrHug** [comment]
I too **vote** in favour.

Quick question, what happens if this rule is adopted while voting is in progress elsewhere? I guess it invalidates votes made at that point in time?

**Comment by arthurbik** [comment]
I **vote** in favor.

@MrHug I don't think that votes are invalidated. How you vote just changes, so the first votes are in words and the last votes use emoticons.

**Comment by pimotte** [comment]
With 3 votes in favour, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 214, I will merge this pull request.

**Pull request merged**
