### PR TITLE
348: Romanian

### PR DESCRIPTION
**Pull request by ManInTheGitHub**
As we are (almost all) trying to abuse Nomic to learn our chosen languages, I felt the need to add Romanian to the list.

P.S.: with a small request: can the people that feel responsible for the already mentioned languages provide the appropriate translations for the more generic title: other languages?

### CODE REVIEW

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
@jdonkervliet I think he also wanted you to tell him how to say "other languages" in Turkish ;)

**Comment by MrHug** [comment]
I leave the Japanese up to @pimotte  by the way ;)

**Comment by jdonkervliet** [comment]
I had to look it up: diğer diller.

**Comment by pimotte** [comment]
@MrHug http://jisho.org/search/other%20languages%20%23sentences is our best friend.

**Comment by MrHug** [comment]
I realise that this vote will be void as soon as Otto fulfills the condition, but here you go anyway

**Comment by MrHug** [comment]
IF @ManInTheGitHub merges https://github.com/ManInTheGitHub/nomic/pull/1 THEN :+1:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
IF rule 336 does not prohibit merging this THEN :+1:

**Comment by pimotte** [comment]
Since 24 hours have passed, I'm resolving my own vote to be :+1: . This means 3/4 (Jesse's vote is invalidated by a commit), so still enough to merge.

**Pull request merged**
