### PR TITLE
Begin of player profiles.

### PR DESCRIPTION
**Pull request by jdonkervliet**
I wanted to add a crafting element to our game, which this _is not_.
This is a spin-off of that idea, where we can collect resources through regular play.
# Profiles

Profiles are meant to describe the play style of the player. Players can
increase or decrease their stats by playing the game.

Currently, there are no rules how to modify these stats, and they are
effectively frozen. 

The stats are bound to specific gameplay elements. The table below gives an
overview of their relation.
1. (von) Karma is a Phoenix Wright reference and should reflect perfection in
   play. For instance, getting a proposal accepted without additions or
   retractions could increase this statistic.
2. Afternoon Naps should reflect activity. An implementation could be the
   inactivity-streak: the number of consecutive days that a player has had no
   visible activity on GitHub.
3. Heart Rate should reflect the number of times you (don't) get what you want.
   For instance, getting a proposal accepted lowers your heart rate, but being
   found guilty increases your heart rate.
4. Hamsters show your supportive role in the game. You could obtain more
   hamsters by voting and making constructive comments on a proposal.

|  | (von) Karma | Afternoon Naps | Heart Rate | Hamsters |
| --- | --- | --- | --- | --- |
| Proposals | x | x | x |  |
| Discussion |  | x |  | x |
| Voting |  | x |  | x |
| Legal |  | x | x |  |

### CODE REVIEW

**Comment by MrHug** [comment]
Stopped reading after noticing that you included a Phoenix Wright Reference

EDIT:

**Comment by MrHug** [comment]
:+1:

**Comment by MrHug** [comment]
In all seriousness though, whereas this non rule-change seems totally fine with me. It can break nothing and in it current state adds nothing except the promise of good stuff in the future.

**Comment by jdonkervliet** [comment]
I thought this to be a good method of introducing this into the game. We can have a conceptual discussion here, than introduce rules about how to increase and decrease these statistics one by one.

**Comment by MrHug** [comment]
Yeah sounds good, because like I said in it's current form this PR literally adds nothing but meaningless text  (according to the rules, not according to me ;))

I don't know how far @pimotte is with depending PRs (although that is a big can of worms...) but that could help out maybe to get somethings through in one go.

**Comment by jdonkervliet** [comment]
We had a discussion about that last week. I'm not sure if he is still planning on adding that, since you can implement the same with using conditional votes.

**Comment by MrHug** [comment]
He seems to be giving it a shot with #74, so I guess a chain of rule-changes can be made after that.

**Comment by pimotte** [comment]
My general view on this idea is: cool stuff! I do want to note that I'd like to try to keep the administration to a managable minimum.

**Comment by jdonkervliet** [comment]
Me too. I'll try to define the rules around these stats in such a way that they can be automated.

**Comment by ManInTheGitHub** [comment]
I like the idea; but shouldn't the 'x' for legal move from "afternoon naps" to "(von) Karma"? In the sense that getting a lawsuit against you would mean you probably play less perfect and thus decrease your " (von) Karma"? Or: you are correcting imperfect play with a lawsuit and thus increase your "(von) Karma".

**Comment by pimotte** [comment]
Also, getting the punishment demanded as a prosecutor would yield (von) Karma :D (but I think the table is more to show the general idea, not so much to fix everything that could be done with this).

**Comment by jdonkervliet** [comment]
Indeed it is to show the general idea. As soon as this is merged, I will file numerous PRs with statistic modifiers.

@ManInTheGitHub Theoretically you can be sued for no reason, which does not mean you are not a perfect player.

**Comment by pimotte** [comment]
:+1:

**Comment by pimotte** [comment]
This is 3/4. I'm merging this

**Pull request merged**
