### PR TITLE
380: Shadows on the Wall

### PR DESCRIPTION
**Pull request by pimotte**
This PR is dependent on #115 

"The direction in which education starts a man will determine his future in life." -Plato

### CODE REVIEW

**Comment by MrHug** [comment]
So if a puppetmaster screws up, do we blame Plato or the puppetmaster?

**Comment by pimotte** [comment]
The puppetmaster. In particular, their responsibilities in these roles only relate to representation-related issues, not game-state related issues. 

I'm still planning to decouple merging and closing of the vote, so the number of actions to which this applies should be fairly limited.

**Comment by MrHug** [comment]
Hmm, can you give an example of a representation-related issue?

**Comment by pimotte** [comment]
Clicking the merge button and labeling issues.

**Comment by MrHug** [comment]
Right ok, yeah I (unfortunately) see few Trials related to that ;)

**Comment by MrHug** [comment]
I'll take a more in-depth look at the content of this PR later today or tomorrow.

**Comment by pimotte** [comment]
I'm actually planning to decouple both of those in order to make sure that for the rules it's always okay, but we can still make use of them for representation purposes.

**Pull request closed without merging**
