### PR TITLE
322: no points for moving things

### PR DESCRIPTION
**Pull request by arthurbik**
I think that moving parts of a rule around should not let a player gain points. Note that the 1 point you gain and the -1 points you gain cancel.

### CODE REVIEW

**Comment by MrHug** [comment]
So why should this not result in a point?

**Comment by arthurbik** [comment]
Because moving things does not change the game.

**Comment by MrHug** [comment]
Well I would argue it does in the same way that for instance transmutation changes the game.
In case of a conflict rules with a lower number have precedence, we are now splitting a rule, thus giving one part of it precedence over the other part.

**Comment by pimotte** [comment]
I'm not a big fan, as reorganizing can contribute value, which should be rewarded. However, if we don't, then we should be consistent and not reward repeals and transmutations either.

**Comment by MrHug** [comment]
I agree with the consistency and still am not in favour of this rule-change ;)

However if we go for consistency I would argue against including repeals in the "0 point changes" as repeals really do change the game.

**Comment by pimotte** [comment]
My criterion was more "contributes effort" and less "changes the game"

**Comment by arthurbik** [comment]
Hmm, I would say that moving a rule does not contribute that much effort... 

I want repeals and transmutations to be rewarded by the way.

**Comment by pimotte** [comment]
:-1:

**Comment by MrHug** [comment]
I am afraid you have not convinced me either...

**Comment by MrHug** [comment]
:-1:

**Pull request closed without merging**
