### PR TITLE
312: Moving rules

### PR DESCRIPTION
**Pull request by MrHug**
As pointed out in issue #19 I would like for this to be possible.

P.S. I'll stop with spamming PRs for a bit now ;)

### CODE REVIEW

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by arthurbik** [comment]
the new rule must self-contained -> the new rule must be self-contained

**Comment by jdonkervliet** [comment]
> In order for this rule-change to be valid, the phrasing of the new rule must identical to the phrasing of the clause or sentence in the old rule and the new rule must self-contained, meaning it does not require a reference to the old rule to be understood.

This could cause conflicts?

**Comment by arthurbik** [comment]
It just makes it very hard to pull of if you don't just copy-paste the whole rule.

**Comment by MrHug** [comment]
@jdonkervliet Can you clarify how it would cause conflicts? (I am presuming you mean Git-based conflicts?)

**Comment by jdonkervliet** [comment]
Making sure that the rule is self-contained while keeping the wording identical can cause difficulties I think.

**Comment by pimotte** [comment]
I'd say that simply means that moving out a part if the wording needs to be changed to do this is disallowed. It could still happen, but in steps, so I don't see that as a problem.

**Comment by jdonkervliet** [comment]
What about: the phrasing must be identical, except when references need to be updated to explicitly refer to the original rule from which the new rule is split off.

**Comment by MrHug** [comment]
I propose to keep this rule as is, i.e. demand exact phrasing and complete independence. New rules can be made that allow for more freedom later, but I can not currently come up with a proper way to phrase more freedom that does not lead to immediate pitfalls.

The rule in it's current form would already allow for rules like 303 to be split.

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by arthurbik** [comment]
I want a clause that states that the old rule must still make sense. We do not want to remove half a sentence from an old rule, leaving it broken.

**Comment by MrHug** [comment]
Although this is a merge commit, I did a bad thing and also included a new addition in it. Thus as per rule 314, a new vote is required.

EDIT: Oh and to make this valid, I'll start of easy.

待った: HOLD IT! (loosely translated, Ace Attorney style)

Hold it!

**Comment by MrHug** [comment]
:+1:

**Comment by arthurbik** [comment]
That reminds me, I still need to watch ep 8 of
http://myanimelist.net/anime/31630/Gyakuten_Saiban__Sono_Shinjitsu_Igi_Ari

**Comment by arthurbik** [comment]
:+1:

**Comment by MrHug** [comment]
@arthurbik Cool, you are watching that too? I didn't know you were a Phoenix fan :D @pimotte and I will probably watch it tomorrow :)

**Comment by arthurbik** [comment]
I am more of an anime fan in general, I haven't played any of the games.

**Comment by MrHug** [comment]
Hmm even more interesting, cause I have been wondering how/if the anime holds up on it's own. I really like it, because it has the same quirky humor as the games and there are many "ah right, that happened" or "ah right that joke" moments, but if you've never played the games those moments can't really happen I guess :P

**Comment by arthurbik** [comment]
The anime to me feel intentionally gamy, which is not a bad thing in this case. The humor works for me, but it bothers me that "guilty until proven innocent"  seems to be the motto in every case.

There are a lot of "ah right, that happened" moments, but there are also a lot of "ah, this is going to be a "ah right, that happened" moment " moments.  All referring to things in the anime and not the games of course.

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
Hmmk, so when merging master back into your branch after your own PR has been accepted, you still need to change point totals. So I guess another revote is required.

**Comment by MrHug** [comment]
:+1:

**Comment by MrHug** [comment]
It's good to see that the humor at least still works and yeah the "guilty until proven innocent" is also the way the courts work in the game.

**Comment by pimotte** [comment]
The way I did this for the other one, is merging master back, stopping the merge by having an empty commit message, then correcting the point total. Git doesn't see it as a conflict, but it is a correct conflict resolution in the semantic sense.

**Comment by MrHug** [comment]
Hmm fair enough, I will do that next time.
Though strictly speaking it is a merge commit that changes something outside of the proposed rule I think...

**Comment by pimotte** [comment]
The rule specifies that the merge commit may **not** affect the proposed rule (hence it may affect point totals). It can't affect other rules either, because that would violate 116.

**Comment by MrHug** [comment]
Fair enough.

**Comment by MrHug** [comment]
@arthurbik If you can repeat your earlier vote, this can be merged ;)

**Comment by arthurbik** [comment]
:+1:

**Comment by pimotte** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 314, I will merge this pull request.

**Pull request merged**
