### PR TITLE
310: Number transmutation

### PR DESCRIPTION
**Pull request by pimotte**
I'd like to make this rule immutable to open up the possibility of a numbering scheme that is more robust to 4 people proposing in parallel.

### CODE REVIEW

**Comment by MrHug** [comment]
In light of #9  I do not think it is a good idea to have this become mutable. I quite like the fact that we simply have successive numbers, eventhough it's a mess to figure this out. I would like some rules in place that would prevent possible abuse of the rule outlined in #9 before voting in favour of this.

EDIT: Perhaps you can tell us how you would propose changing this rule if it becomes mutable.

**Comment by pimotte** [comment]
I was thinking something along the lines of everyone taking the first number higher than the last proposal which is equal to the number in the player list, modulo (the number of players + 1). This would enable parallel drafting a bit more without people assigning the same numbers to things.

**Comment by MrHug** [comment]
But it would make prime numbers even more unlikely for some players based on their place in the player list. Thus giving them unfair advantage if #9 is accepted.

**Comment by pimotte** [comment]
I'm aware. A pretty good reason to reject #9, if you ask me:P

**Comment by MrHug** [comment]
Or a pretty good reason to reject this one ;)

**Comment by pimotte** [comment]
I might actually be okay with not passing this at this time. The numbers in the titles already improve a lot.

**Comment by MrHug** [comment]
Personally　I do believe that is good enough and I quite like the safety of knowing that numbering successively is harder to overturn without my approval. The numbers of rules are actually quite important in several rules already and I can see them become more important in others later on.

**Comment by MrHug** [comment]
:-1:

**Comment by pimotte** [comment]
I withdraw this proposal.

**Pull request closed without merging**
