### PR TITLE
Put rules where they belong.

### PR DESCRIPTION
**Pull request by jdonkervliet**
Something weird was going on with the positioning of some of the rules.

### CODE REVIEW

**Comment by pimotte** [comment]
I'm going to suggest we view this as being part of #45

**Comment by pimotte** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by arthurbik** [comment]
:+1:

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by pimotte** [comment]
Merging this with unanimity.

**Pull request merged**
