### PR TITLE
Started playing.

### PR DESCRIPTION
**Pull request by jdonkervliet**

### CODE REVIEW

**Comment by MrHug** [comment]
Closed but not merged?

**Comment by pimotte** [comment]
I force-pushed the spelling fix which auto-closed the PR.

**Comment by MrHug** [comment]
Ah ok, so should @jdonkervliet and I Make New PRs or will you force us in? Otherwise I feel rule 205 would give us a 0.5% advantage.

Edit: Can we somehow add links to the rules? E.g. make them headers? That way we can link to them in PRs easier.

**Comment by jdonkervliet** [comment]
What does rule 205 have to do with joining the game?

I am in favor of @pimotte adding us to the player list, since we agreed offline that we would join the game.

**Comment by MrHug** [comment]
Ah my initial reading of 212 had caused me to conclude that PR === Rule change, but this is of course not the case. It merely states that a rule change has to be made by means of a PR. Also is @thegeman joining for this? 

I will try to make a PR on my phone through SSH on my Pi ;)

**Comment by pimotte** [comment]
Agreeing with @MrHug regarding the PR !== rule change. I'm okay with adding you guys myself, but for the sake of consistency I'd rather you guys make your own PR

**Comment by jdonkervliet** [comment]
Tim is not joining.

If you add me it gets done faster, so I opt for that.

**Comment by MrHug** [comment]
Keep up Jesse, we Are already added through a PR ;)

**Pull request closed without merging**
