### PR TITLE
Non-rule change: Add profile for Pim Veldhuisen

### PR DESCRIPTION
**Pull request by pimveldhuisen**
~~In this PR, updating my profile, one commit hash containing the English dictionary word six-letter accede 
is present, making the PR eligible for a point according to rule 369: Hash Brownie Points.~~

In other, possibly related news, my .git directory for this repo now contains over half a million files.

EDIT: The PR now contains one hash containing a six-letter word, and another hash containting a five-letter word.

### CODE REVIEW

**Comment by MrHug** [comment]
> In other, possibly related news, my .git directory for this repo now contains over half a million files.

Why?

Also it is an unwritten rule to name PRs that do not outline a rule change as "Non rule change: X"

EDIT: For clarification. It is not mandatory to do so (at least I do not think so, I ought to check the rules on it), but the idea is that is helps create a clear overview of what type of PRs are currently open.

**Comment by Jason-Statham** [comment]
MrHug edited a message. The previous content of the message was:

> In other, possibly related news, my .git directory for this repo now contains over half a million files.

Why?

Also it is an unwritten rule to name PRs that do not outline a rule change as "Non rule change: X"

**Comment by pimveldhuisen** [comment]
> > In other, possibly related news, my .git directory for this repo now contains over half a million files.
> 
> Why?

Do you think it was a mere coincidence that the hash contained a 6 letter word? I may have some commits in my reflog that are no longer attached to any branch.

Regarding the Non-rule change: I am working on extensive legislation to rectify any and all ambiguities regarding the different types of PRs.

**Comment by MrHug** [comment]
Hahaha looks like we have gained a serious player :smile:
Good to hear your first real PR is also on it's way.

Also consider this my first and last warning regarding committing an action that would allow me to put you on Trial. If you want that point, you better make sure to include the obtaining of that 1 point in this PR ;) Next time I'll just put you on Trial, even if I have no hopes of winning because: a) I can. b) it's fun. and c) I can :)

**Comment by pimveldhuisen** [comment]
I am pretty sure the rule that imposes a duty to explicitly mention points gained is no longer on the books.
Rule 532 currently states:

```
Upon request of another player, the initiator of a PR must state how many points their PR adds to their score as a result of which specific point-awardable conditions.
```

Also, I think my PR clearly mentions my eligibility for the point?

**Comment by MrHug** [comment]
Correct. But I meant that you need to add it to your total in this PR, it currently says you have 0 points ;)

**Comment by pimveldhuisen** [comment]
I was told by @pimotte that it is allowed to update the profile later, so if you will sue me i will sue him for misinforming me ;). An obligation to include score changes in the PR itself also provides some practical issues, since one cannot know the url of the PR before the PR is created. (In this case one could make a pretty good guess, but still)

**Comment by MrHug** [comment]
Yeah I usually end up guessing. I agree that this table is irrelevant and can be updated later, but the score always needs to be up to date. See rule 328, specifically:

> The total score of the player must reflect the gamestate.

So the table can be empty sure, but your line that says: 

> Current score: 0 (line 5)

should read:

Current score: 1

EDIT: If only you or I could sue @pimotte for misinformation... I think there are two problems though:
1. Communication took place outside of GitHub, so as far as the game is concerned it did not exist.
2. Misinforming someone is not technically a violation of the rules. In fact I would argue it might not even be "against the spirit of the game", although a jury might disagree with me there.

**Comment by Jason-Statham** [comment]
MrHug edited a message. The previous content of the message was:
Yeah I usually end up guessing. I agree that this table is irrelevant and can be updated later, but the score always needs to be up to date. See rule 328, specifically:

> The total score of the player must reflect the gamestate.

So the table can be empty sure, but your line that says: 

> Current score: 0 (line 5)

should read:

Current score: 1

**Comment by pimveldhuisen** [comment]
Ah I see you are correct. Ironically however, changing the score in this case would also not result in a valid gamestate.

**Comment by MrHug** [comment]
Why not? When this PR is merged I think you would be entitled to a point,
so the only way to get that is by adding it in this PR?

**Comment by pimveldhuisen** [comment]
~~But changing the PR would also change the commit hash?~~
Fake edit: Ah this could ofcourse be in a seperate commit. Elric has deeply engraved rebasing and squashing in my mind.

**Comment by Jason-Statham** [comment]
pimveldhuisen edited a message. The previous content of the message was:
~But changing the PR would also change the commit hash?~
Fake edit: Ah this could ofcourse be in a seperate commit. Elric has deeply engraved rebasing and squashing in my mind.

**Comment by MrHug** [comment]
Correct a separate commit does the trick. And brownie points indeed imply
rebasing is a bad idea.

**Comment by pimveldhuisen** [comment]
I've updated the PR accordingly ;)

**Comment by pimotte** [comment]
To clarify: My remark IRL about updating profiles referred to the list of PRs. The point total is part of the gamestate, which should explicitly be correct. See 309.

**Comment by pimveldhuisen** [comment]
I see. I went for internal consistency within the file itself, but I see how immediately updating the point total and noting the changes later works beter, and is in line with the rules.

Note that the PR now adheres to rule 309. I guess that it can thus be voted on?

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by MrHug** [comment]
Btw, I see you now have 2 points in your profile... How many extra commits did the message with "added" cost you? :P

**Comment by pimveldhuisen** [comment]
Since added is a five-letter word, it was significantly easier.  Also, once I had my scripts properly set-up, it was not that much hassle.

**Comment by pimotte** [comment]
3/5 is merge.

**Pull request merged**
