### PR TITLE
Judgement changes

### PR DESCRIPTION
**Pull request by arthurbik**
Hopefully this makes rule 210 well-defined.

### CODE REVIEW

**Comment by MrHug** [comment]
Hmm I like it, but this assumes that judgement happens through github issues rather than in PRs? I suppose this is fine, but just wanted to make sure of the nomenclature used.

**Comment by pimotte** [comment]
I like the general idea of this. I'm a little iffy on equality between "invoked judgments" and "open issues". We might want to use issues for general discussion too, but you'd skip out on your possibility to be judge if you have an open issue. Furthermore, we might want to have some way to have a fallback in case there are no valid judges. This is not so much an issue in the default rules, because there is only one player taking a turn, but there may be multiple people invoking judgement/having open issues.

**Comment by MrHug** [comment]
Agreed with the fallback. I suppose the easiest solution is to consider all users except the issue creator, thus including others with open issues.

Edit: regarding using issues. We can add a judgement label for this purpose and refer to this in the rule.

**Comment by arthurbik** [comment]
We should decide whether a Judge is allowed to change the rules as a resolution of conflicts. If so, we should use PRs in stead of issues. If not, how about we use issues with "Judgement" in the title?

@MrHug  That should work, but then I should also have to add that a Judge cannot invoke Judgement.

**Comment by MrHug** [comment]
Hmm sure that is fine I guess. But as it stands the game can not progress when judgement is invoked because no new turns can be taken right? Thus I do not think judgement can be invoked when one is already active?

I do not think rule change is allowed. As I think rule 211 stipulates that an unsolvable conflict is the end of the game.

**Comment by arthurbik** [comment]
New turns can be taken when a majority of the other players allows it, but personally I would not find it a problem if the game cannot progress when Judgement is invoked.

My question is: What is a "solution of a conflict"?

**Comment by MrHug** [comment]
True, but I think changing that to not progressing would be fine (at least for now).

A solution is a verdict on legality by the judge and the closing of the issue, I would say. It can be reopened with any overruling/objections by others provided the rules still allow that (I.e. no turn has ended yet).

**Comment by arthurbik** [comment]
I would say that an objection which is not an attempt to overrule is the same as invoking Judgement again.

**Comment by MrHug** [comment]
Right, but a judge won't object to his own judgement thus not invoke judgement again right? At least that would be weird.

**Comment by pimotte** [comment]
Comments: "not a Judge at any time by" reads kind of confusing. I thought it was the "at any time" referred to "being a Judge" and not "invoking Judgement". I'd move this to some other place.

"Judge is not longer a Judge" -> "Judge is no longer a Judge"

"When Judgment has been invoked, a player may not begin a turn or start a vote without the consent of a majority of the other players. This does not include starting a vote for consent to begin a turn, start a vote or overrule a Judge's Judgement." This is quite convoluted. Mainly because we don't really have a definition for "starting a vote". What about just limiting this to a prohibition to start the turn and allow a vote    to provide for exceptions?

Also, the number of the rule needs to be updated to 305.

**Comment by MrHug** [comment]
Agree with all of @pimotte's comments. Also, am I just missing it, or did you forget to include the "no applicable judges" clause?

Also:

> a player who can shall close all open issues labelled "Judgement" in a timely fashion

Um, shouldn't only the settled issue be closed?

**Comment by arthurbik** [comment]
The same Judge settles all current Judgements. So why not all at once? I would also say that when a Judge is overruled on one point, the Judge is overruled on all points currently being decided.

**Comment by arthurbik** [comment]
I still see Judgements occurring at the same time as one conflict that the Judge resolves. @MrHug  Do you want to change that?

**Comment by MrHug** [comment]
I just hadn't considered it that way, but it sounds good to me. I don't think we'll have more than one (unrelated) conflict at the time anyway, otherwise we can deal with it then/after.

**Comment by MrHug** [comment]
I see you changed it to majority vote in case no judge is possible, this seems fine to me. Food for thought: you are not allowed to vote for yourself and voting will continue until a winner is decided upon?

I **vote** in favour of this rule-change.

**Comment by arthurbik** [comment]
I **vote** if favor.

Maybe we need a rule stating that you cannot vote on your own proposed rules.

**Comment by pimotte** [comment]
I **vote** in favour. The only doubt that remains is the voting in case of no possible Judge, but that could at most cause an infinite loop which we can break ourselves, hence not ending the game. 

With regards on voting on your own proposal, I'd be more inclined to include something that says you automatically vote for your own rule.

**Comment by pimotte** [comment]
With 3 votes in favour, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 214, I will merge this pull request.

**Pull request merged**
