### PR TITLE
Non-rule-change: Scripts

### PR DESCRIPTION
**Pull request by pimotte**
Feel free to use the script. Don't forget to swap in your own username and create a file "password" with your password. Don't commit that. Also check the results. (For me #22 was missing)

### CODE REVIEW

**Comment by MrHug** [comment]
IF @pimotte runs this for me and puts my PRs in my file THEN :+1:

**Comment by jdonkervliet** [comment]
IF @pimotte runs this for me and puts my PRs in my file THEN :+1:

**Comment by pimotte** [comment]
Note that the fancy votes don't work since my commits invalidate them.

**Comment by MrHug** [comment]
Awww... We should maybe have a clause for that, cause I see this as a good application for conditional votes.

**Comment by MrHug** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by pimotte** [comment]
3/4 is merge

**Pull request merged**
