### PR TITLE
351: Goodbye

### PR DESCRIPTION
**Pull request by MrHug**
Let's prepare better for random players.
I will only claim the 0.1 point for the quote here and not for the translation as I will not provide one (have fun
@pimotte)

> 「命あるものが、自分を守るため戦うのは、当然のことだ。
> “人間”だからこそ‥‥だれかのために、戦える
> ‥‥だれかのために、どれだけ強くなれるか‥‥？　それこそが人間の価値
> 弁護士は、つねにその価値を試される、戦士なんだ‥‥
> 戦いの末に結ばれた《絆》は、たとえ、断ち切られても‥‥かならず、よみがえる。
> ‥‥何度でも」 (Phoenix Wright, Phoenix Wright Ace Attorney: Trials and Tribulations)

That took forever to find, I hope it is right... And for the first time it is actually the second part of the quote that I want to emphasize, rather than the first bit.

### CODE REVIEW

**Comment by pimotte** [comment]
It is living things, for which fighting in order to protect themselves, is natural.
"Being human", for this reason (we) fight for the sake of someone.
... For somone's sake, how strong can we become?  It is to the extend of human life's worth.
Lawyers are always tested by this worth, like soldiers.
The bonds that tie the end of the battle, if they too were to be cut, than necessarily, were ressurected, any number of times.

/\ Initial attempt without looking at the original English translation.

At the end of the battle, if the bonds that connect us are severed, we are resurrected, any number of times.

/\ Last sentence corrected after reading to yield a clunky, but approximately correct, translation.

**Comment by MrHug** [comment]
Ok I'll give a go at the English version from memory:

"It is only natural for living creatures to fight, to protect their own lives. 
But what makes us human, is that we fight for others.
But who do we fight for and how hard must we fight?
Those are the true measures of what human life is worth.
We defense attorneys are warriors constantly challenged by those questions.
Even when the battle is over, and the bonds that tie us are severed.. We always return, time and time again."

**Comment by pimotte** [comment]
I'd like to add in "activity in pimotte/nomic", if potential newcomers have other github projects they deem more important, then that shouldn't make a difference towards their hiatus status.

**Comment by MrHug** [comment]
Haha fair enough, I'll add that in :)

**Comment by ManInTheGitHub** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by pimotte** [comment]
4/4 is merge

**Pull request merged**
