### PR TITLE
304: Precedence

### PR DESCRIPTION
**Pull request by MrHug**
In order to further simplify our rules I propose an amendment in the way rule conflicts are handled.

Also, as `adda` turns out to be an English word, this will net me two points (unless a rebase is required, but obviously I will not rebase, but rather merge this time around :P)

### CODE REVIEW

**Comment by pimotte** [comment]
You changed "numerical method" to "the method above" in one place, but not the other. There's also a lack of "else" in the numbered list, which could lead to confusion. The numbers imply an ordering, but as phrased, there could be a situation where no priority can be determined if 1 and 2 conflict.

**Comment by MrHug** [comment]
Handled your comments, they were fair points :)

**Comment by pimotte** [comment]
One more remark: 2 refers to "the prime rule", which as in 1, would refer to a rule with a prime number. I propose changing this to "the rule which has this property" in 2.

**Comment by arthurbik** [comment]
So if two prime rules ever conflict with each other, the game ends?

**Comment by MrHug** [comment]
@pimotte  Aw, I was hoping to pull that trick in my favour at some point. Sure I will change it.
@arthurbik nope cause the rules only apply if "only one" is prime. Otherwise it's the same as the old situation.

**Comment by jdonkervliet** [comment]
This is insane. I **vote** against.

**Comment by MrHug** [comment]
Care to elaborate? I figured not all rules are created equal and we can't have rule conflicts be easy to solve, where is the fun in that?

**Comment by pimotte** [comment]
I can kind of see Jesse's point. I'd probably be okay with 1, but 2 seems excessively convoluted.

**Comment by MrHug** [comment]
Alright alright, let's have it just be rule 1 then :cry:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by MrHug** [comment]
@pimotte Ok maybe we need the "merge conflict resolved does not require revote" rule ;P

**Comment by arthurbik** [comment]
I don't really see why this is better.

**Comment by arthurbik** [comment]
:-1:

**Comment by jdonkervliet** [comment]
:-1:

**Comment by Jason-Statham** [comment]
test

**Comment by Jason-Statham** [comment]
test

**Comment by Jason-Statham** [comment]
I think this pull request is rejected.

**Comment by Jason-Statham** [comment]
I think this pull request is rejected.
cry

**Comment by MrHug** [comment]
Well it seems this is rejected then. I'll close this PR for now.

**Pull request closed without merging**
