### PR TITLE
365: Fixed eligible voters to players

### PR DESCRIPTION
**Pull request by MrHug**
This PR is dependent on #95.

### CODE REVIEW

**Comment by MrHug** [comment]
I've included some of your comments (only required 11 rebases and at least 30 "git rebase --skip" commands).

Let me know if you want anything else changed.

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
Alright, that's one :D Only 1 more left now @jdonkervliet, @ManInTheGitHub (or 2 so we don't have to wait till tomorrow)

**Comment by MrHug** [comment]
Well let's get this show on the road already...

@ManInTheGitHub, @jdonkervliet consider this my warning for closure in 72 hours. As the votes stand right now, it would be merged with 2/2 votes in favour.

@jdonkervliet your objection against warnings in #95 doesn't stand, as this is a new PR :wink:

**Comment by jdonkervliet** [comment]
I don't have time to read it now. I can do so in the weekend probably.

**Comment by MrHug** [comment]
After a discussion with @pimotte today we concluded that I am not allowed to merge this, unless I issue the warning on all of the open PRs. Now I would be perfectly willing to do so, but I think it would be better if either @jdonkervliet or @ManInTheGitHub were to just read this ;)

By the way, I know you said something about doing this on the weekend @jdonkervliet (although I do not blame you for not doing it) but why is this comment gone?

**Comment by ManInTheGitHub** [comment]
:+1:

**Comment by jdonkervliet** [comment]
@MrHug what are you talking about? That comment is still there..

**Comment by Jason-Statham** [comment]
jdonkervliet edited a message. The previous content of the message was:
@MrHug what are you talking about? That comment is still there.

**Comment by jdonkervliet** [comment]
Holy shit, we're back online.

**Comment by jdonkervliet** [comment]
I'm not gonna read this btw:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
Oh you're right, well I guess my desktop just decided not to show it to me then...

**Comment by MrHug** [comment]
With 4/4 votes this can now be merged. However as this is the first time we are merging a chain of PRs I will come by @pimotte later and do the merging together with him (don't worry I'm happy to take the responsibility for violations) to ensure that we merge properly.

**Comment by pimotte** [comment]
I'm pretty sure everything should be fine if you press the button on this PR.

**Pull request merged**
