### PR TITLE
317: Let's make 315 immuatable

### PR DESCRIPTION
**Pull request by MrHug**
I think it that we can safely say that we want voters to have one vote, unless they have special rules that we can agree upon in later rules. But every eligible voter should in my mind always have at least the right to vote, it's kinda implicit already.

### CODE REVIEW

**Comment by pimotte** [comment]
You do realize that by making this immutable, this rule will always have priority over any special roles we would create (by 110)? Hence we would need to transmute this back to mutable before we could do something like that.

**Comment by MrHug** [comment]
Well no, not if we say things like:

"Role X is defined as follows: blablabla. This role replaces the role of eligible voter for case Y"
Or alternatively:
"Role X is defined as follows: blablabla. This rule has precedence over any other rules regarding number of votes assigned to a role."

**Comment by pimotte** [comment]
I disagree. 105 specifies that every player is an eligible voter, hence that cannot be taken away by an immutable rule. Same holds for the second formulation. The rule that allows rules to claim precedence is mutable, hence it does not trump 110.

**Comment by MrHug** [comment]
Oh right that's only when mutable rules conflict (I was thinking of rule 209 to help me out). Perhaps, another amendment is first required...?

**Comment by pimotte** [comment]
I'd say creating a rule saying "every eligible voter has at least one vote" and making that immutable achieves what you're looking for?

**Comment by MrHug** [comment]
Actually no. I also want it to be possible to take away the right to vote in certain cases, but I guess we need to make the "every player is an eligible voter"  mutable for that first...

**Comment by MrHug** [comment]
Ok so I've done some more thinking on this and I guess this is how I see it:
- Eligible voters should always have one vote (thus this rule should still be immutable).
- However, not all players are necessarily always eligible voters (e.g. punishments after Trials, or other constructs in the future). Thus in my opinion, the next move should then be to make rule 105 mutable.
- Finally we should update rule 203 to refer to "players with a right to vote".

**Comment by pimotte** [comment]
How is that better than creating new mutable rules which state that sometimes eligible voters can have no votes? This seems kind of convoluted to obtain the same effect.

Alternative construct: Define the notion of abstaining from a vote, then as a punishment force people to abstain.

**Comment by MrHug** [comment]
Because the very notion of an "eligible voter" to me means that they should be allowed to vote. A voter without votes makes no sense to me (nomenclature wise), this is also why I proposed #23. In my opinion the notion of an "eligible voter" should always imply the ability to vote, thus it is the role of "eligible voter" that we need to be able to take a way or replace with other rules, rather than changing the meaning of that role.

**Comment by pimotte** [comment]
I see why you would like to have it this way considering the naming. However, this construction seems needlessly complicated. We would also need to take away the eligible voter role for a role with more than one vote, which makes even less sense to me.

**Comment by MrHug** [comment]
Not necessarily take it away, more like "upgrade it". I think any other construct, whilst having less rule changes required right now, will only lead to a more convoluted naming scheme.

**Comment by arthurbik** [comment]
I support this rule change. 

My point of view for who can vote: I don't want to prevent people from voting. If you want to force people to vote, add a rule defining what a majority vote is and state in that rule that a voting round may end before everyone has finished voting after "enough" time has passed.

**Comment by pimotte** [comment]
But how would you "upgrade it" without removing the title of eligible voter?

**Comment by pimotte** [comment]
I'm actually also in favour of a construct @arthurbik would suggest, which is basically abstaining by absence.

**Comment by MrHug** [comment]
I'm going to take a little more time to think this over, but I still think that "eligible voters"  having the right to vote should be without doubt. Never mind crazy other schemes I might be thinking of, I feel this is so fundamental that it should be kept as such. 

I am currently considering a rephrase of 315 to "at least one vote" first, but I'll sleep on it ;)

**Comment by MrHug** [comment]
Right well let's explore other options first. I'll close this PR for now.

**Pull request closed without merging**
