### PR TITLE
315: Eligible voters are the the ones that vote

### PR DESCRIPTION
**Pull request by MrHug**
Not players, but voters do the voting. This may look like a trivial change, but I wanted to make this rule immutable and I figured we should right this wrong before even considering immutability.

### CODE REVIEW

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
I thought this was a mistake I made, but this is actually in the original ruleset.

**Comment by MrHug** [comment]
Hmm, strange as it makes the notion of an "eligible voter" quite abundant...

**Comment by pimotte** [comment]
Not at all, since the existence of this rule allows to create roles which allow more than 1 vote, for instance.

**Comment by pimotte** [comment]
Or punishments that take away voting rights.

**Comment by MrHug** [comment]
Hmm I hadn't considered that.  But I think this rephrase still allows that ;)

**Comment by arthurbik** [comment]
Since there isn't a rule that states that "only players are eligible voters", I can see one future problem with this rule change and zero benefits. Can you give an example of how this rule-change makes things better?

**Comment by pimotte** [comment]
Rule 105 states that every player is an eligible voter, which makes 'being an eligible voter' regulated, and hence by rule 116 a non-player is necessarily not an eligible voter unless a rule states otherwise, in my interpretation.

In my opinion, it makes it better, because it makes the ruleset as a whole more correct, in my opinion.

**Comment by MrHug** [comment]
I agree with @pimotte 

Generally speaking in my opinion the notion of votes only makes sense in the context of eligible voters and not in the context of "players" or "participants" in the game.

**Comment by arthurbik** [comment]
Should this be number 316?

**Comment by MrHug** [comment]
No I think #12 should be 307, thus this can remain at 315 ;)

**Comment by arthurbik** [comment]
私は賛成票を投じます - I cast a vote in favor.
私 - I
は - I am the one doing the voting
賛成票 - affirmative vote
を - the next verb does something to the proceeding 
投じる - to cast, the ます makes it polite (since Google translate is polite apparently)

**Comment by arthurbik** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by arthurbik** [comment]
A commit on a pull request dated after any votes resets those votes, unless this commit is a merge commit resulting from a merge from master on pimotte/nomic to the source branch of the pull request and does not alter the proposed rule-change.

Right?

**Comment by MrHug** [comment]
Correct I didn't check properly, I thought that "MrHug referenced this pull request 5 hours ago
 Open
315: Judgement #12" was also a commit ;)

**Comment by MrHug** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 306, I will merge this pull request.

**Pull request merged**
