### PR TITLE
Structure.

### PR DESCRIPTION
**Pull request by jdonkervliet**
Please accept. This PR is a lot of work. :cry: 

Bu çok zor. This is very hard.

### CODE REVIEW

**Comment by pimotte** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by MrHug** [comment]
There is no Japanese or Turkish yet...

**Comment by jdonkervliet** [comment]
Fixed.

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
jdonkervliet voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Pull request merged**
