### PR TITLE
Added Turkish phrase to rule name

### PR DESCRIPTION
**Pull request by jdonkervliet**
It had to be done.

### CODE REVIEW

**Comment by MrHug** [comment]
A PR on a PR... What do the rules say about that I wonder? :P

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by jdonkervliet** [comment]
I think I read somewhere that it was OK. Don't remember where or when.

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by jdonkervliet** [comment]
Not all was italics.

**Comment by pimotte** [comment]
Since only PRs to master are regulated, I'm going to claim PRs to non-master to be unregulated and just fall within my jurisdiction as owner of this repo and merge this. (Just as I have made a PR to Arthur in the past)

**Pull request merged**
