### PR TITLE
366: Conditional Transfers

### PR DESCRIPTION
**Pull request by MrHug**
Active bribing should be supported ;)

### CODE REVIEW

**Comment by pimotte** [comment]
IF at least two of #83, #84, #96 and #97 are merged THEN :+1:

**Comment by MrHug** [comment]
Why are you making your battle my battle?

**Comment by pimotte** [comment]
Because you're human, so you'll fight to protect my life. Nomic is life.

**Comment by MrHug** [comment]
I'll protect nomic sure, but I see no reason to protect "your nomic". What does that even mean?

**Comment by pimotte** [comment]
Haikus are easy
But sometimes they don't make sense
Refrigerator

**Comment by jdonkervliet** [comment]
> The Sender in a Transfer X can add conditions to those outlined in the rules that make that specific Transfer X valid.

Change to:

> The Sender of a Transfer X can add extra conditions to Transfer X in addition to those outlined in the rules.

**Comment by MrHug** [comment]
Changed + added another clause about contradictory conditions.
All votes reset.

**Comment by MrHug** [comment]
So since @jdonkervliet is on holiday, let's get this through  now.

Consider this my 72 hour warning (@jdonkervliet, @pimotte, @ManInTheGitHub)

**Comment by ManInTheGitHub** [comment]
Not a fan of bribing :) so: what seems to be missing is how to reject. Ignore?

**Comment by MrHug** [comment]
You mean how to reject a transfer?

Hmmm that never was explitly possible.. I guess that you indeed ignore ;)

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
Well those 72 hours have passed by now ;)

**Comment by MrHug** [comment]
With 2/2 votes in favour, I'm merging.

**Pull request merged**
