### PR TITLE
Non Rule Change: For shame!

### PR DESCRIPTION
**Pull request by MrHug**
We are playing a game all about rules and we didn't use any of Gibbs Rules yet...
To make up for this I want to at least rename rule 101 in honour of Gibbs' wife.

> Gibbs: "Have you got a rule for everything?"
> Shannon: "Working on it... Everyone needs a code they can live by"

I'll work on ways to include things like:

Rule 13: "Never, ever involve lawyers"
Rule 38: "Your case, your lead"
And of course Rule 9: "Never go anywhere without a ~~usb-stick~~ knife"

For an outdated list of rules see [this awesome youtube video](https://www.youtube.com/watch?v=eKBbfNrv4ns).

### CODE REVIEW

**Comment by pimotte** [comment]
Which wife was that? :p

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
The only one that really mattered ;)

**Comment by pimotte** [comment]
Ooh, the redhead. Also, kind of ironic how this has "non-rule change" in the title. xD

**Comment by ManInTheGitHub** [comment]
I must admit I had never heard of this... then again: I also don't see a problem with the change :)

**Comment by ManInTheGitHub** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:shipit:

**Comment by pimotte** [comment]
3/4. Technically.

**Pull request merged**
