### PR TITLE
318: making is possible to end a vote early

### PR DESCRIPTION
**Pull request by arthurbik**

### CODE REVIEW

**Comment by pimotte** [comment]
I like that this is only for simple majority votes. I would like to specify a specific time frame, though. Perhaps 72 hours?

Also, may warn the other players (is singular in text)

**Comment by MrHug** [comment]
Hmm.... I would also like to specify a time, but also the option to block this before hand.
Take @pimotte's short break coming up for instance. In his absence only two of us would need to ally to push through a million PRs...

**Comment by arthurbik** [comment]
As for the Japanese:
待ったをかけない (DON'T HOLD IT!)

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by arthurbik** [comment]
:+1:

**Comment by MrHug** [comment]
After merge conflicts have been resolved, this PR should be ready to be merged.

EDIT: As I am not sure the GH web-interface allows you to do this, I could do so in your stead if you want me to @arthurbik

**Comment by arthurbik** [comment]
That would be great @MrHug. But maybe wait until the trial has been resolved?

**Comment by MrHug** [comment]
Technically speaking this is not mandatory. I could if you wanted me to though, but I think you should retract your vote for now then ;)

EDIT: see #35

**Comment by jdonkervliet** [comment]
Jason, are you there?

**Comment by arthurbik** [comment]
I do not actually have any problem with it being merged, but it seems to be a good idea to await the resolution of #35

**Comment by MrHug** [comment]
@jdonkervliet, clearly not?

**Comment by jdonkervliet** [comment]
Ikr. :(

**Comment by MrHug** [comment]
Do you have @Jason-Statham running somewhere I can also access? I won't touch anything, but wouldn't mind looking around ;)

**Comment by jdonkervliet** [comment]
Prepare for great code:
https://github.com/jdonkervliet/nomic-bot

**Comment by MrHug** [comment]
Hmm cool and when should this code trigger? Every comment?

**Comment by jdonkervliet** [comment]
Pretty much.

**Comment by MrHug** [comment]
Hmm ok, well then I would say he only needs to post after a ":+1:" or ":-1:" post, otherwise this will become annoying real fast :stuck_out_tongue_winking_eye: Other than that, it looks cool :)

**Comment by jdonkervliet** [comment]
Bla!

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by jdonkervliet** [comment]
IT LIVES!

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by jdonkervliet** [comment]
:wave:

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by jdonkervliet** [comment]
Okay, so now @Jason-Statham should only respond when you say his name, or perform a vote action.

**Comment by Jason-Statham** [comment]
pimotte voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by jdonkervliet** [comment]
I don't think I get what this rule-change is for. What is a use-case for ending a vote early?

**Comment by MrHug** [comment]
Basically the following:

Imagine you and I have a great idea for a new rule, but for whatever reason @pimotte and @arthurbik decide not to comment on it at all, I can say: "In 72 hours this vote will be closed", that means that at that time we tally up the votes and find 2 out of 2 votes (yours and mine) in favour, thus the rule is accepted.

> and the rule is adopted when a majority of the votes **that are cast** are in favor of the rule-change

(Emphasis mine)

**Comment by jdonkervliet** [comment]
Shit. I'm definitely going to forget to object...

**Comment by MrHug** [comment]
Well if someone says: "This vote will be closed in 72 hours" and you get that e-mail, objecting will be very simple to do right?

**Comment by jdonkervliet** [comment]
Yes. I respond to all my email within 72 hours, no matter what.

**Comment by MrHug** [comment]
Well no and I'm not saying that I do that either, but that is not a manner of "forgetting", but just "not wanting to". Those are two different things :)

**Comment by pimotte** [comment]
I've taken the liberty to fix the merge conflict, but as @arthurbik, as the initiator, has expressed preference to wait with merging until after trial, I won't do that just yet.

**Comment by MrHug** [comment]
Now that the Trial is over, I guess this can be merged? Judgement only freezes new PRs, not the merging of existing ones, right?

**Comment by jdonkervliet** [comment]
It says starting turns, so yeah.

**Pull request merged**
