### PR TITLE
328: Organising users

### PR DESCRIPTION
**Pull request by MrHug**
Now this is very much a WIP PR, so there is no need to vote yet, after all I would have to organize these userfiles otherwise merging this PR will result in an invalid state. Just wanted to get some opinions on the idea, before doing this.

### CODE REVIEW

**Comment by pimotte** [comment]
The violation part is kind of nasty. Say that for some reason, someone else edits my player file, then they get put on trial if I fail to update it in a rule-change with points.

**Comment by MrHug** [comment]
Right... But the last player is also not good for the same reason (if you mess it up and someone touches it, they shouldn't be put on Trial either). 

I still think the first person to F it up should be put on Trial, as they are the ones that cause the gamestate to be corrupted. If you continue working with this corrupt gamestate (for instance, because we do not notice), then they are still to blame in my opinion, no matter how much more you might mess up.

**Comment by pimotte** [comment]
The situation I was describing is:
1. Jesse adds a ":)" to my player file.
2. I propose a rule change without editing my player file, failing to record the point.
3. Jesse gets sued, since he's the one that edited my file.

In this scenario, he did absolutely nothing wrong. 

Maybe do something like "whoever merged the pull request that caused the inconsistency in the game state"?

Edit: That last one should maybe be a general rule.

**Comment by MrHug** [comment]
Right, fair enough. 

I already have a slight fear for merging PRs, adding such a general rule will ensure I triple-check everything twice :stuck_out_tongue_winking_eye: That being said, it might not be a bad idea.

**Comment by arthurbik** [comment]
>  The total score of the player should reflect the gamestate. If this file does not match the game state, the merger of the Pull Request that led to a divergence in gamestate can be put on Trial for violation of this rule.

Why not just say

>  The total score of the player must reflect the gamestate. 

It is then implicit that the one who caused the error broke a rule.

**Comment by pimotte** [comment]
I think Arthur's proposal should work. I'm guessing it's fairly evident who caused the divergence, if not, we can do a Judgement on it in the specific situation where it is not clear.

**Comment by MrHug** [comment]
I changed things :)

**Comment by pimotte** [comment]
The one table doesn't seem to render properly, I think you need another newline above them.

**Comment by MrHug** [comment]
Fixed the rendering issue, as far as I am concerned we can merge this?
EDIT: Once we get the votes in ofc ;)

**Comment by pimotte** [comment]
Players can enter with a non-zero amount of points, which would then not be recorded.

**Comment by MrHug** [comment]
Yeah I just thought of that whilst @ManInTheGitHub was joining... I'll fix that ;)

**Comment by MrHug** [comment]
As I can not change 2 rules in one PR, it will have to be like this for now untill we change rule 213

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
With 3 out of 4 votes in favour and the PR dating 14 days back, this can be merged.

**Pull request merged**
