### PR TITLE
336: Minimum duration

### PR DESCRIPTION
**Pull request by MrHug**
I would like some more time for debate and discussion to prevent situations like #57.

This way everyone at least can get their say in before a PR is merged, giving them the chance to point out errors others might not have noticed.

尾外刈り　(In judo: "large" "outward" "hook")

### CODE REVIEW

**Comment by pimotte** [comment]
I would be okay with this. I also feel obligated to point out there's 1.1 points and a lack of foreign languages and/or quotes.

**Comment by MrHug** [comment]
I hereby claim the 0.1 point as should be done.

**Comment by pimotte** [comment]
Note that I specifically left out that clause in the language rule, because it's annoying as fuck. :)

**Comment by MrHug** [comment]
Meh

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
Ok so this can be merged now, just not sure whether or not we can, as this rule specifies we need a 24 hour period, but I guess we only need that after this has been merged right (no ex post facto shizzle)

**Comment by pimotte** [comment]
I agree this can be merged now, since there's currently no rule that prevents you from clicking the button. After clicking the button, you would not have been allowed to click the button.

**Comment by pimotte** [comment]
:wave:

**Comment by pimotte** [comment]
I'm going to claim that I can retract the vote, because the merging of the PR completes the vote, and hence adoption has not occurred yet.

**Comment by pimotte** [comment]
I'd like to have this say "a PR that needs to be voted on", since otherwise new players would have to wait 24 hours to join.

**Comment by MrHug** [comment]
Hmm fair point, I'll add that in.

**Comment by MrHug** [comment]
Done

**Comment by pimotte** [comment]
Maybe non-rule-change PRs too? See: #66

**Comment by MrHug** [comment]
Nah, because of the potential hazards that what some people consider fixing a spelling/grammar mistake, other people might consider a rule-change. So I would like everyone to have the chance to take a look at that.

**Comment by pimotte** [comment]
Okay with me, it was just a thought.

**Comment by MrHug** [comment]
Fair enough ;)

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
With 3 out of 4 votes in favour, this can be merged.

**Pull request merged**
