### PR TITLE
337: The right to appeal

### PR DESCRIPTION
**Pull request by MrHug**
Prosecution is also allowed to appeal now. 

"What about me!? Don't I get to prosecute anyone!?" (Winston Payne, Apollo Justice Ace Attorney)

I claim my 0.1 point.

### CODE REVIEW

**Comment by pimotte** [comment]
I'd rather move in the opposite direction: Burden of proof is on the prosecution, they have one shot. If we were to have enough people for higher courts, then this would be okay, but for now I'd actually prefer having a "double jeopardy" rule.

**Comment by MrHug** [comment]
Hmm... I could live with another rule for double jeopardy, but in case of a Guilty, but no punishment Verdict? I would like to be able to appeal then I guess?

**Comment by MrHug** [comment]
(Also note that the whole notion of appeals is hypothetical so far, as we have far to few players for it...)

**Comment by MrHug** [comment]
In accordance with rule 318 I am moving for a forced vote on this issue. If you don't like it that is fine, but in 72 hours this PR is closing one way or another unless someone objects ;)

**Comment by pimotte** [comment]
:-1:

**Comment by jdonkervliet** [comment]
:-1:

**Comment by MrHug** [comment]
Yeah well, too bad then :)

**Pull request closed without merging**
