### PR TITLE
327: Quoting time

### PR DESCRIPTION
**Pull request by MrHug**
> “We demand rigidly defined areas of doubt and uncertainty!”
> (Douglas Adams, The Hitchhiker's Guide to the Galaxy)

### CODE REVIEW

**Comment by jdonkervliet** [comment]
:-1:

**Comment by MrHug** [comment]
I am having trouble understanding the negative vote by @jdonkervliet. With the millions of movies on your IMDB watchlist and your memory for quotes, this should be right up your alley

**Comment by jdonkervliet** [comment]
Let's make this rule more positive by changing 'the omission of a quote as punishable' to 'the addition of a quote as rewarding', for instance by giving points for it.

I don't like increasing the number of possible offenses.

**Comment by MrHug** [comment]
But a free point for a quote seems a bit overkill to me... I know @pimotte
will kill me for this, but how about 0.1 point then :wink:

**Comment by jdonkervliet** [comment]
Yes! That sounds great.

**Comment by pimotte** [comment]
Then I have no choice but to kill you both.

I would be okay with that if there's some sort of clause that says you may claim a point by submitting a PR, referencing all the places where you did that, and you may only claim whole points.

**Comment by jdonkervliet** [comment]
Why only whole points?

**Comment by pimotte** [comment]
Because fractional points would make even more of a mess than already here.

**Comment by jdonkervliet** [comment]
There is no mess. I am highly in favor of adding more rewards to the game. We can do this by either raising the win-condition and increasing the number of points for rule-changes, or we simply change the minimum point unit to 0.1, and achieve the same thing.

**Comment by pimotte** [comment]
I've thought about this, and I'm okay with fractional points, if the fractions are 1/10^n, with n > 0.

**Comment by MrHug** [comment]
I hereby claim my 0.1 points for the quote in the PR message above.

**Comment by pimotte** [comment]
You're trying to gain points for something that is currently not in the rules. I'm pretty sure you can't do this. The rule will only go into effect upon merge.

**Comment by MrHug** [comment]
Yeah but at that time I am entitled to the 0.1 point right? So the only way for me to get that is by  already including the update in this PR...?

**Comment by pimotte** [comment]
Mmm. I'm still this doesn't oppose 107. But given I can see your interpretation too, I'll let it slide.

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by pimotte** [comment]
:+1:

**Comment by Jason-Statham** [comment]
jdonkervliet voted in favor.
MrHug voted in favor.
pimotte voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by pimotte** [comment]
I was about to merge this. 

していない。＝ I'm not doing it.

**Comment by pimotte** [comment]
:+1:

**Comment by Jason-Statham** [comment]
jdonkervliet voted in favor.
MrHug voted in favor.
pimotte voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
jdonkervliet voted in favor.
MrHug voted in favor.
pimotte voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
jdonkervliet voted in favor.
MrHug voted in favor.
pimotte voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by jdonkervliet** [comment]
Where it that gif from?

**Comment by MrHug** [comment]
giphy.com search for "pity"

**Comment by jdonkervliet** [comment]
Oh.

**Comment by pimotte** [comment]
We're there, finally. 3/4, I'll merge this.

**Pull request merged**
