### PR TITLE
325: Fairer start

### PR DESCRIPTION
**Pull request by MrHug**
Anyone know how to more properly format this, suggestions are welcome.

Basically if a new player joins in 3 months, I want him to start with more than 0 points.

### CODE REVIEW

**Comment by arthurbik** [comment]
You could always just use words if you don't like the formatting.

What if people have negative points by that time?

**Comment by MrHug** [comment]
The max(0, x) prevents the score of the new player from becoming negative.

EDIT: As getting negative points is currently (and I believe should remain) only possible for violations, new players should not be punished for violations of others.

**Comment by MrHug** [comment]
Let me just make sure my implicit vote will not be 汚い (dirty), by which I mean invalid (though I have no idea how to say that in Japanese).

**Comment by pimotte** [comment]
無効（むこう), which I looked up for a sentence elsewhere.

On a more serious note, I disagree that it's unfair later joiners start with 0 points. Besides the fact that this game is a little bit like whose line (Everything's made up and the points don't matter), points somewhat represent effort put into the game.

**Comment by MrHug** [comment]
Well I could go for the cop-out and say: if they don't matter, then why not give them to them?
But generally, I agree that the points don't matter, but an outsider who is not yet involved in the game might not realize this. Basically I want to make it more new-player friendly in the hopes of enticing some more people to join us ;)

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by arthurbik** [comment]
:+1:

**Comment by Jason-Statham** [comment]
jdonkervliet voted in favor.
MrHug voted in favor.
arthurbik voted in favor.
That is 3 out of 4 players. This PR should be merged. I cannot do that yet.
happy

**Comment by MrHug** [comment]
That was quite a pain to merge...

**Comment by MrHug** [comment]
And it seems I failed, let's have a revote :(

**Comment by MrHug** [comment]
5000 commits later...

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by arthurbik** [comment]
Say a player has significantly less points than the other players, what prevents that player for forfeiting the game and joining the game again?

**Comment by MrHug** [comment]
Currently nothing, though I would argue that the points are not reset then. That player, with that GH handle, still has a number of merged PRs, a number of trials against him etc.

**Comment by MrHug** [comment]
@pimotte Opinions on this?

I will fix the merge conflict later ;)

**Comment by pimotte** [comment]
I don't like it, but it appears to have passed, so you can fix the conflict then merge?

**Comment by MrHug** [comment]
It hasn't passed. By merging failed last time, so we needed a revote.

EDIT: Ah yes with Arthur gone it has passed ofc...

**Comment by pimotte** [comment]
As I see it, there's a vote from Jesse after the wrong merge. Given Arthurs absence, that's enough.

**Comment by MrHug** [comment]
As I see it I do not have to add the 0.1 point to my total right? If so, then this can be merged I guess ;)

**Comment by pimotte** [comment]
I agree, per the Ex Post Facto Prohibition

**Comment by MrHug** [comment]
Oh... I just thought the rule allows you to take the 0.1 point, but does not require you to do so? I think I would be entitled to it?

**Comment by pimotte** [comment]
Oh, that too. I'd be fine with either interpretation until we have a better definition of moment on effect, state, continuous effect, etc.

**Comment by pimotte** [comment]
Since this is 2/3 votes and Stefan doesn't seem to want to claim the 0.1, I'll merge this to make room for others.

**Pull request merged**
