### PR TITLE
321: Retracting votes

### PR DESCRIPTION
**Pull request by MrHug**
As we recently found out, it can sometimes be good to be able to retract votes. In light of possible automation later down the line (right @jdonkervliet, @Jason-Statham ?), I figured a rule for this would be 面白い (interesting).

### CODE REVIEW

**Comment by arthurbik** [comment]
This is confusing if a vote is already completed and a pull-request is already merged.

**Comment by MrHug** [comment]
Fair point, I've added a clause that covers this.

**Comment by pimotte** [comment]
The nomenclature is "adopting a rule-change", not accepting it. Otherwise, looks good to me.

**Comment by jdonkervliet** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by arthurbik** [comment]
:+1:

**Comment by pimotte** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 314, I will merge this pull request.

**Pull request merged**
