### PR TITLE
339: Drugs rule

### PR DESCRIPTION
**Pull request by MrHug**
"Weed card, it's what I need. Hardly ever... Okay, always. But it's not an addiction, cause my doctor gave me a
prescription." (Garfunkel and Oates, Weed Card)

I claim my 0.1 point for this quote.

This way we are always allowed to demand "gedoog" a violation, as in we acknowledge the crime (Guilty), but do not
subtract points. Note that it does still require the defense to demand a 0 point penalty. It is just that the defendant
can never be forced to choose between: Not Guilty and a guaranteed penalty. Thus rules such as: A violation that
requires a gamestate reversal should require at least a one point verdict if the defendant is found Guilty" are
prohibited.

### CODE REVIEW

**Comment by pimotte** [comment]
This overrides the "jury cannot assign less points than the defendant suggests" clause. I'm guessing that's not intentional?

**Comment by MrHug** [comment]
That's true... Hmm but do you get what I mean? If so, do you have suggestions for a rephrase?

**Comment by pimotte** [comment]
"except if the defendant pleads for a certain minimum punishment"?

**Comment by MrHug** [comment]
Fair enough, added that in.

**Comment by jdonkervliet** [comment]
How is this not already allowed? A defendant can plead Guilty and suggest a 0 point reduction, right? Also, I don't think the quote conveys the message you had in mind.

**Comment by MrHug** [comment]
Well yes a defendant can do that, however in the future a rule that states:

"A defendant found Guilty of a violation that requires a game-state fix should always be punished by at least one point"

could be accepted. I want to prevent this. There should be no "minimum punishments" in our rules, the minimum punishment should always be 0 points, never more.

EDIT: The quote is indeed not completely relevant, but it's a good song.

**Comment by jdonkervliet** [comment]
If you would like to prevent that, what about voting against such a rule change?

**Comment by jdonkervliet** [comment]
oops, wrong button.

**Comment by MrHug** [comment]
Well my vote is only one, having this rule would make sure that it becomes harder to get such a rule in ;)

**Comment by jdonkervliet** [comment]
So far I don't see the point.

**Comment by jdonkervliet** [comment]
:-1:

**Comment by MrHug** [comment]
Well like I said earlier, having this rule would make it harder for new rules to pass that want to impose a minimum penalty on certain violations. I would like that safety, but if you guys don't then I am afraid there is little I can do... ;)

**Comment by jdonkervliet** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:wave:

**Comment by jdonkervliet** [comment]
Okay, the problem I have with this rule is that the formulation is not generic.
I would change it to something along the lines of:

Minimum penalties in the form of a reduction of points (or some other resource) are not valid.

**Comment by MrHug** [comment]
In all fairness at the time of writing the very notion of other things than points had never been mentioned anywhere (it still hasn't been mentioned in any rule at this time ;), but sure I can change that ;)

**Comment by MrHug** [comment]
Made it more generic ;)

**Comment by jdonkervliet** [comment]
Now I would like for the defendant to _not_ have control over the minimum penalty.

**Comment by MrHug** [comment]
Hmm, so you would like the minimum to just always be 0, even if the defendant says: I did it, I should be penalized by 100 points?

Admittedly I am not opposed to that, the defendant still can say that he feels he deserves to be penalized in a certain manner, however with no control over it, the jury can ignore that. I quite like the idea of the defense setting the lower bound and the prosecution setting the upper bound of a Verdict if the defendant is found Guilty.

**Comment by jdonkervliet** [comment]
I would prefer if we let the Judge set the lower bound in all cases. I like the idea of the defendant being incapable of hurting himself, even if it is voluntary.

**Comment by MrHug** [comment]
Hmm, but there is no Judge in a Trial, so I guess you mean the jury? If so then it should be removed from this rule and from rule 324 I guess. So you could condition your vote on that ;)

**Comment by MrHug** [comment]
Ok I'll be closing this PR for now and we can try this again later at some point, or not ;)

**Pull request closed without merging**
