### PR TITLE
308: Plugging some loopholes

### PR DESCRIPTION
**Pull request by MrHug**
As I explained to @jdonkervliet yesterday, this only specifies a PR needs to be merges. Thus merging a PR into my own PR would allow me to get points. This is probably not preferred

### CODE REVIEW

**Comment by MrHug** [comment]
I'll fix the merge conflict when I am not on my phone ;)

**Comment by pimotte** [comment]
Needs a number change on the rule (and a back-merge).

**Comment by MrHug** [comment]
Fixed :wink:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
:+1:

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by jdonkervliet** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 214, I will merge this pull request.

**Pull request merged**
