### PR TITLE
335: Unmuting win-inflexibilty

### PR DESCRIPTION
**Pull request by pimotte**
これは勝つのを違います。= This changes winning.

This PR changes 112 from immutable to mutable.

I would like the Trophy-game-continuing measure to take effect, and this needs to be unimmutabilitied for that.

### CODE REVIEW

**Comment by MrHug** [comment]
Whereas I too like the idea of the trophy system, I would like to explore alternative possibilities first. With our current playerbase of only 3 players rules can be changed very easily, meaning that any immutable rule that is mutable suddenly becomes a potential hazard...

**Comment by pimotte** [comment]
To be honest, I'd have no problems repealing this rule all together. In my opinion it's not too essential for the game to be un-constitutioned.

**Comment by MrHug** [comment]
Well that is definitely a step too far for me. I want immutable rules at all times, in fact I would like more of them, rather then less.. ;)

**Comment by MrHug** [comment]
So regarding this PR, I would like to be convinced no suitable alternatives exist ;)

**Comment by pimotte** [comment]
Rephrasing trophies such that it's a "after a player wins" rule, instead of "instead of winning". But that feels dirty.

**Comment by MrHug** [comment]
Why? That sounds like a perfect solution to me... ;)

**Comment by pimotte** [comment]
Let's go there, then. I'm withdrawing this rule-change proposal.

**Pull request closed without merging**
