### PR TITLE
316: Naming rules

### PR DESCRIPTION
**Pull request by pimotte**
I feel this will help us refer to rules, especially ones that we might commonly refer to.

お名前は？= May I have your name? (This is a contracted form, but the お in front of なまえ is an honorific prefix, signalling that the speaker has respect for the person whose name is requested, leading to the formal English in the translation.)

### CODE REVIEW

**Comment by arthurbik** [comment]
Something about uniqueness.

The rules already have names: their numbers. I agree that some constructions should have names, but this is already possible, like Judgement.

**Comment by pimotte** [comment]
The titles are more of a mental-use construct, not for use in rules text. (In fact, the titles are not to be used in any rules, since the titles themselves are not part of the rule.)

This is more to enable us to refer to a rule informally. (I.e. saying "Simple majority" instead of rule 203 in discussion).

Because they are not used in rules, I don't necessarily think they need to be unique, but if you'd like that, I could add that in.

**Comment by MrHug** [comment]
Is there currently a rule that forbids us to give the rule a name in this manner?

**Comment by pimotte** [comment]
Currently naming a rule in this manner would make it part of the rules text. This is also more of an "encourage-good-habits" kind of rule, rather than a "block-everything" kind of rule.

**Comment by MrHug** [comment]
Right... Well I am not necessarily a fan of good habits, but with a uniqueness clause I guess I could be swayed to vote in favour.

**Comment by pimotte** [comment]
:+1:

**Comment by MrHug** [comment]
Hmm I am afraid I still would like another clause...

"Changes to rules that only change or introduce rule names are allowed to be combined in a single turn."

Or something of that effect. I do not want one PR for every rule that we want to name after this rule has been passed.

**Comment by pimotte** [comment]
I'd say #28 suffices for that :)

**Comment by jdonkervliet** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by MrHug** [comment]
Now that #28 has passed, I will vote in favour after the merge conflict has been resolved (be sure to ping me when you resolve them, @pimotte)

**Comment by pimotte** [comment]
@MrHug 採決してください。

**Comment by MrHug** [comment]
:+1:

**Comment by Jason-Statham** [comment]
More votes are needed!

**Comment by jdonkervliet** [comment]
This can be merged, right?

**Comment by MrHug** [comment]
Good to see I am not the only one finding it scary to hit the "merge"-button, but yes I guess so?

Mine and Pim's vote are after some Japanese for sure and yours is too as the opening post contains some.

**Comment by pimotte** [comment]
I was just waiting it out since you merged the other one as well, and it would be kind of ugly if we both did the finishing post.

I will round this up.

**Comment by pimotte** [comment]
With 3 votes in favor, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 318, I will merge this pull request.

**Pull request merged**
