### PR TITLE
344: No bribes

### PR DESCRIPTION
**Pull request by MrHug**
No bribing allowed, at least not this conspicuously.... :wink:

### CODE REVIEW

**Comment by pimotte** [comment]
:+1:

**Comment by jdonkervliet** [comment]
:+1:

**Comment by MrHug** [comment]
One more hour untill the 24 hour period I think ;)

**Comment by ManInTheGitHub** [comment]
:+1:

**Comment by MrHug** [comment]
With 4/4 votes in favour, I am merging this.

**Pull request merged**
