### PR TITLE
Repealing rule 208

### PR DESCRIPTION
**Pull request by pimotte**
Being bounded by arbitrary limits is for lesser mortals.

### CODE REVIEW

**Comment by MrHug** [comment]
I actually considered this rule change myself, but I am not sure about the need for it right now. I mean we are only at 14 rules at the moment, why should we abolish the limit already?

**Comment by jdonkervliet** [comment]
I would like to replace this rule with a more sophisticated version. In stead of a hard limit, e.g., set a rule on how rules should be combined.

**Comment by pimotte** [comment]
I'm not sure this needs any more explanation than the commit message:)

**Comment by MrHug** [comment]
Hmm @jdonkervliet  Interesting suggestion, but I do not see how combining would work out.

**Comment by arthurbik** [comment]
About repealing rule 208:
If we want to repeal rule 208 eventually, now is the best time to do so opposed  to when we have 25 mutable rules. When we have 25 rules (or a bit less and some proposed rules), people might want to block a repeal of rule 208 just to block the creation of some particular new rule.

About @jdonkervliet 's idea:
I think combining rules can only be done on a case by case basis. Creating a rule about this therefore seems hard to do well.

**Comment by pimotte** [comment]
So, to kick things off, I **vote** in favour.

**Comment by jdonkervliet** [comment]
I also **vote** in favor.

**Comment by MrHug** [comment]
@pimotte  So you need to vote on your own rules? That seems counter-intuitive ;)

Regardless, I also **vote** in favour of this rule.

**Comment by arthurbik** [comment]
I **vote** in favor.

**Comment by pimotte** [comment]
With 4 votes in favour, among 4 players, a simple majority has been achieved, so by rule 203, the suggested rule-change is adopted. As prescribed by rule 214, I will merge this pull request.

**Pull request merged**
